### ISSUE TITLE
有个蓝牙设备在android4.3上可以连接成功，但是在7.0上就是不可以连接上

### ISSUE THREAD

**Issue by xsfgdut** [xiaoyaoyou1212/BLE#14]
有个蓝牙设备在android4.3上可以连接成功，但是在7.0上就是不可以连接上，不知道为什么？求助
附上log如下：
04:14.944 14746-14746/com.vise.ble I/BluetoothDevice: connectGatt
03-23 18:04:14.944 14746-14746/com.vise.ble D/BluetoothGatt: connect() - device: 98:7B:F3:5F:C9:CF, auto: false
03-23 18:04:14.944 14746-14746/com.vise.ble D/BluetoothGatt: registerApp()
03-23 18:04:14.944 14746-14746/com.vise.ble D/BluetoothGatt: registerApp() - UUID=0b4c17ec-57ce-453d-8e9e-ddce49e5e287
03-23 18:04:14.951 14746-14816/com.vise.ble D/BluetoothGatt: onClientRegistered() - status=0 clientIf=11
03-23 18:04:14.952 14746-14746/com.vise.ble I/HwPointEventFilter: do not support AFT because of no config
03-23 18:04:14.964 14746-14746/com.vise.ble D/android.widget.GridLayout: horizontal constraints: x2-x0>=1312, x2-x1<=427, x1-x0<=369 are inconsistent; permanently removing: x2-x1<=427. 
03-23 18:04:14.964 14746-14746/com.vise.ble D/android.widget.GridLayout: horizontal constraints: x2-x0>=1312, x2-x1<=32, x1-x0<=239 are inconsistent; permanently removing: x2-x1<=32. 
03-23 18:04:14.984 14746-15107/com.vise.ble D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
03-23 18:04:15.038 14746-15107/com.vise.ble D/OpenGLRenderer: endAllActiveAnimators on 0x79167f6c00 (RippleDrawable) with handle 0x79167db080
03-23 18:04:15.273 14746-15078/com.vise.ble D/BluetoothGatt: onClientConnectionState() - status=0 clientIf=11 device=98:7B:F3:5F:C9:CF
03-23 18:04:15.273 14746-15078/com.vise.ble I/Bluetooth:(ViseBluetooth.java:116).onConnectionStateChange: onConnectionStateChange  status: 0 ,newState: 2  ,thread: 10815
03-23 18:04:15.274 14746-15078/com.vise.ble D/BluetoothGatt: discoverServices() - device: 98:7B:F3:5F:C9:CF
03-23 18:04:24.967 14746-14746/com.vise.ble D/BluetoothGatt: close()
03-23 18:04:24.968 14746-14746/com.vise.ble D/BluetoothGatt: unregisterApp() - mClientIf=0
03-23 18:04:24.969 14746-14746/com.vise.ble I/Bluetooth:(DeviceControlActivity.java:68).onConnectFailure: Connect Failure!
03-23 18:04:24.972 14746-14746/com.vise.ble D/HwRTBlurUtils: check blur style for HwToast-Toast, themeResId : 0x7f09008a, context : com.vise.ble.DeviceControlActivity@39a21c9, Nhwext : 5, get Blur : disable
03-23 18:04:25.049 14746-14746/com.vise.ble I/HwPointEventFilter: do not support AFT because of no config
03-23 18:04:25.079 14746-15107/com.vise.ble D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
03-23 18:04:35.789 14746-14759/com.vise.ble D/BluetoothGatt: onClientConnectionState() - status=0 clientIf=11 device=98:7B:F3:5F:C9:CF
03-23 18:04:35.790 14746-14759/com.vise.ble I/Bluetooth:(ViseBluetooth.java:116).onConnectionStateChange: onConnectionStateChange  status: 0 ,newState: 0  ,thread: 10811
03-23 18:04:35.790 14746-14759/com.vise.ble D/BluetoothGatt: close()
03-23 18:04:35.790 14746-14759/com.vise.ble D/BluetoothGatt: unregisterApp() - mClientIf=0
03-23 18:04:35.814 14746-14746/com.vise.ble I/Bluetooth:(DeviceControlActivity.java:77).onDisconnect: Disconnect!

**Comment by xiaoyaoyou1212** [comment]
@xsfgdut 你们要做7.0的适配么，这个我还没试过，目前仅试过了6.0系统是可以的，手上还没得7.0系统的测试机没法调试额
