### ISSUE TITLE
自動連接設備

### ISSUE THREAD

**Issue by pranavlathigara** [xiaoyaoyou1212/BLE#15]
有沒有任何自動連接到特定設備的選項？

**Comment by xiaoyaoyou1212** [comment]
@pranavlathigara 这个设备必须通过扫描发现后再进行连接的，你说的自动连接是？

**Comment by pranavlathigara** [comment]
我的意思是一旦連接丟失，那麼當設備進入範圍時，它會自動連接到特定的設備。

**Comment by xiaoyaoyou1212** [comment]
@pranavlathigara 框架中提供了是否自动连接这个参数的，demo中传的是false，没做自动连接，因为自动连接功能比较耗时

**Comment by wmailn** [comment]
没找到demo里哪里设置的自动连接..

**Comment by wmailn** [comment]
@xiaoyaoyou1212 能说一下哪里设置自动连接吗？
