### ISSUE TITLE
api扫描有两种方法，我用哪种呢？

### ISSUE THREAD

**Issue by liunewshine** [xiaoyaoyou1212/BLE#16]
应该是类库自动判断调用那个api才对

**Comment by xiaoyaoyou1212** [comment]
@liunewshine 由于两个扫描方式有很大不同，不太好统一处理，所以都提供了接口，上层根据需求自己选择扫描方式，其实两种方式提供的信息基本都差不多，因为我的扫描结果也是做了相关处理的。
