### ISSUE TITLE
小米手机蓝牙扫描不到小米手机（2s/5c）

### ISSUE THREAD

**Issue by aiybybz** [xiaoyaoyou1212/BLE#19]
demo案例 为什么小米手机蓝牙扫描不到小米手机（2s/5c）

**Comment by xiaoyaoyou1212** [comment]
@aiybybz 这个是针对低功耗设备的扫描，你说的那个需要传统蓝牙才能扫描到，具体区别可以看看http://blog.csdn.net/xiaoyaoyou1212/article/details/51854454

**Comment by aiybybz** [comment]
好的，感谢作者。
