### ISSUE TITLE
写数据失败报Initiated Exception Occurred! 错

### ISSUE THREAD

**Issue by Darksiderlyd** [xiaoyaoyou1212/BLE#2]
private IBleCallback bleWriteCallback = new IBleCallback() {

@Override
public void onSuccess(Object o, int type) {
if (o == null) {
return;
}
if (o instanceof BluetoothGattCharacteristic) {
if (((BluetoothGattCharacteristic) o).getValue() == null) {
return;
}
BleLog.i("Send onSuccess!");
Toast.makeText(mContext, "写成功", Toast.LENGTH_SHORT).show();
List<BluetoothGattDescriptor> descriptors = ((BluetoothGattCharacteristic) o).getDescriptors();
for (BluetoothGattDescriptor descriptor : descriptors) {
Log.d("notifysuccessws", HexUtil.encodeHexStr(descriptor.getValue()));
}
Log.d("notifysuccessw", HexUtil.encodeHexStr(((BluetoothGattCharacteristic) o).getValue()));
}
}

@Override
public void onFailure(BleException exception) {
if (exception == null) {
return;
}
Toast.makeText(mContext, "写失败", Toast.LENGTH_SHORT).show();
BleLog.i("notify fail:" + exception.getDescription());
}
};

写失败的时候 BleLog.i("notify fail:" + exception.getDescription()); 打印出来是 
public class InitiatedException extends BleException {
public InitiatedException() {
super(BleExceptionCode.INITIATED_ERR, "Initiated Exception Occurred! ");
}
} 中的 Initiated Exception Occurred! 
这个代表的是谁初始化错误了

**Comment by xiaoyaoyou1212** [comment]
这个表示你写入数据失败了，`getBluetoothGatt().writeCharacteristic(characteristic)`这个返回false
