### ISSUE TITLE
由于连接和配对是不一样的，所以我一直得不到连接状态

### ISSUE THREAD

**Issue by aer874475222** [xiaoyaoyou1212/BLE#21]
你代码中获取到的是配对状态，所以我建议加个获取连接状态方法，还有下面这个获取所有已连接的设备
bluetoothManager.getConnectedDevices(BluetoothProfile.GATT_SERVER);

**Comment by xiaoyaoyou1212** [comment]
@aer874475222 没太看明白，ViseBluetooth中提供了getState获取状态的方法，包含扫描连接的状态，配对状态属于设备的信息，所以扫描后就直接显示出来了，判定以前有没有配对过。
