### ISSUE TITLE
Can't find BLE devices on some phones

### ISSUE THREAD

**Issue by aaayushsingh** [xiaoyaoyou1212/BLE#24]
works on my Redmi note 3(android 6.0), but doesn't detect any devices on moto g5 plus(android 7.0), and lenovo (android 6.0)

**Comment by xiaoyaoyou1212** [comment]
@aaayushsingh 只能扫描到低功耗设备，不能扫描手机，具体可以查看文档中的FAQ介绍

**Comment by aaayushsingh** [comment]
@xiaoyaoyou1212 I was scanning for low energy device using my phone. 
Your app detects BLE devices when it is installed on my phone, but does not detect any BLE device when installed on MOTO g5 or Lenovo k4 note.

**Comment by xiaoyaoyou1212** [comment]
@aaayushsingh 你用其他手机有没有试过，或者扫描其他BLE设备，我这里没有你说的这两款手机所以不能验证你这个问题，但我们公司提供的二三十款测试机没有发现该情况，公司提供的BLE设备是nordic芯片的。

**Comment by shouyuandong** [comment]
Android 6.0 以上的设备，需要打开 GPS，并申请定位服务。可以试一下

**Comment by ContentPane** [comment]
Android 6.0 以上的设备，需要打开 GPS，并申请定位服务.感谢楼上老哥!!
