### ISSUE TITLE
这个怎么搜索不到我的设备呢

### ISSUE THREAD

**Issue by kanglanlan** [xiaoyaoyou1212/BLE#25]
只能搜索到一个周边没这个蓝牙，开了好几个手机还有硬件设备，都搜索不到。

**Comment by xiaoyaoyou1212** [comment]
@kanglanlan 设备必须是低功耗设备才能搜到，可以看看FAQ的相关解释

**Comment by YuPf1989** [comment]
我也是，搜索不到任何蓝牙设备，有ble设备也搜不到，用其他的框架是没问题的

**Comment by xiaoyaoyou1212** [comment]
@YuPf1989 有没有换个手机试试，可以进群讨论，看看具体是因为什么问题导致的
