### ISSUE TITLE
通知回调的问题？

### ISSUE THREAD

**Issue by stormlei** [xiaoyaoyou1212/BLE#27]
通知的回调里面，得到数据后，TextView.setText() 显示数据，然后吧数据传到上一个页面。再打开该页面，在通知回调里面TextView.setText()  就不起作用了，返回的值不能显示到TextView上，搞了好久，不知道什么原因？ @xiaoyaoyou1212

**Comment by xiaoyaoyou1212** [comment]
@stormlei 是不是蓝牙连接断开导致的问题呀，数据处理最好用一个类统一获取再进行分发。
