### ISSUE TITLE
扫描超时的回调不执行

### ISSUE THREAD

**Issue by 632610503** [xiaoyaoyou1212/BLE#28]
测试手机是乐视2，Android版本 6.0。设置好超时时间之后，超时回调并不会执行，而是一直扫描下去。同时我注意到扫描和连接的方法都是2个版本的，是不是需要个人在使用时判断系统版本来调整呢？

**Comment by xiaoyaoyou1212** [comment]
@632610503 用一个方式扫描就行，demo中有注释讲解，还有这个超时不回调看看是不是那个回调处理不一致导致的，最好对照demo看看

**Comment by 632610503** [comment]
@xiaoyaoyou1212  好的  多谢，对照Demo再试试。
