### ISSUE TITLE
BluetoothGattCallback::onCharacteristicRead函数处理问题

### ISSUE THREAD

**Issue by chenmtech** [xiaoyaoyou1212/BLE#29]
在onCharacteristicRead函数中，
for (IBleCallback bleCallback : bleCallbacks) {
                        if (bleCallback instanceof ICharacteristicCallback) {
                            if (status == BluetoothGatt.GATT_SUCCESS) {
                                ((ICharacteristicCallback) bleCallback).onSuccess(characteristic);
                            } else {
                                bleCallback.onFailure(new GattException(status));
                            }
                        }
                    }
removeBleCallback(tempBleCallback);
问题1：为什么要遍历bleCallbacks，只要是ICharacteristicCallback，都用onSuccess或onFailure处理一次呢？如果我对不同的characteristic进行了读写操作，或者对同一个characteristic进行了读和写操作，那么在bleCallbacks中就会有多个ICharacteristicCallback，用每个回调都去处理读回的characterisitc，岂不是混乱了？
问题2：每次对Characteristic操作时，对Descriptor操作时，包括读Rssi时，都调用了listenAndTimer()，其中用tempBleCallback保留最新的操作回调。在onCharacteristicRead()，为什么要把最新的tempBleCallback回调remove呢？

**Comment by xiaoyaoyou1212** [comment]
@chenmtech 目前该库有些地方处理确实是有隐藏问题，当时也是为修复问题好多地方没考虑全，目前正在考虑重新规划该库，如果有兴趣的话希望能参与进来！
