### ISSUE TITLE
导入androidstudio报错

### ISSUE THREAD

**Issue by alienzh** [xiaoyaoyou1212/BLE#3]
你好，我想运行你得示例，当我导入androidstuido的时候报错了
错误如下：Error:Could not get unknown property 'VERSION_NAME' for project ':baseble' of type org.gradle.api.Project.
请问下，这个是我配置问题，还是示例本身问题呢，望回复，谢谢！

**Comment by xiaoyaoyou1212** [comment]
我运行是没问题的哟，看错误是提示你找不到versionName这个配置，我demo中是写的1.0，你是在外部使用了这个配置吧。
