### ISSUE TITLE
扫描过滤条件增加

### ISSUE THREAD

**Issue by kanshenmekan** [xiaoyaoyou1212/BLE#30]
可以指定uuid[]的service扫描方法，指定特定的devicename和MAC地址也可以传入list或者数组表示过滤多个名字或者mac的。。

**Comment by xiaoyaoyou1212** [comment]
@kanshenmekan 目前在第二版中已实现，更多过滤规则可以自己实现，考虑到目前第二版没那么快发布，你可以参考里面的实现逻辑。

**Comment by xiaoyaoyou1212** [comment]
第二版已经发布，这些功能基本都已实现，具体可查看使用文档。
