### ISSUE TITLE
EDR的蓝牙设备也使用这一套吗？

### ISSUE THREAD

**Issue by adbGitHub** [xiaoyaoyou1212/BLE#31]

**Comment by xiaoyaoyou1212** [comment]
@adbGitHub 你这个是蓝牙增强速率，2.x以后就出来了，蓝牙在4.0后被分为高速蓝牙、传统蓝牙以及低功耗蓝牙，每个负责的方面不同，高速蓝牙主攻数据交换与传输，传统蓝牙则以信息沟通、设备连接为重点，低功耗蓝牙最主要就是降低功耗，在物联网方面应用较多，该库就只是针对低功耗蓝牙的。
