### ISSUE TITLE
直接调用MAC 地址 的connect 方法，一直连不上。。。Timeout Exception Occurred

### ISSUE THREAD

**Issue by Sabirjan** [xiaoyaoyou1212/BLE#33]
直接调用MAC 地址 的connect 方法，一直连不上。。。Timeout Exception Occurred
时间设置的20秒

**Comment by xiaoyaoyou1212** [comment]
@Sabirjan 这个是超时异常，有用demo试过没，正常的扫描能扫到并连接么
