### ISSUE TITLE
使用connectByName连接成功后，调用isConnected返回true，几秒后再次调用则为false

### ISSUE THREAD

**Issue by bbdlg** [xiaoyaoyou1212/BLE#34]
虽然isConnected返回false，但数据通信正常。
之前用ViseBluetooth.getInstance().connect不会出现此种现象。
等待时间在10秒以上即可复现。

**Comment by YuPf1989** [comment]
遇到了同样的问题。。。
设备建立连接后，调用ViseBluetooth.getInstance().isConnected();返回值为false，但设备可以通讯

**Comment by xiaoyaoyou1212** [comment]
这个是因为第一版将扫描状态也加进来了，在扫描的时候进行判定就会有这种问题。目前第二版

**Comment by xiaoyaoyou1212** [comment]
这个是因为第一版是针对单个设备的管理，扫描和连接状态没有区分，你这个问题出现应该是由于在扫描第二个设备时进行判定。目前第二版已经全新改版，也支持多设备连接，建议接入最新的第二版。
