### ISSUE TITLE
大佬能否添加一个获取某一个serviceUUID下面的所有characteristicUUID的值

### ISSUE THREAD

**Issue by zhang40bu** [xiaoyaoyou1212/BLE#50]
bindChannel(BluetoothLeDevice bluetoothLeDevice, PropertyType propertyType, UUID serviceUUID,
                                 UUID characteristicUUID, UUID descriptorUUID) 
这个方法只能拿到具体的一个 characteristicUUID 的值。
而如果需要那某一个 serviceUUID下的所有 的  characteristicUUID 的值，就不会写了。期待群主能加上。谢谢。另外上次给您的高低位的转换方法（已经得到我的验证）请加到工具类中。谢谢。

**Comment by zhang40bu** [comment]
同时加一个例子，把循环服务得到的值存在一个对象中。给对象赋值。这样就太完美了。谢谢群主。蓝牙服务中给的数据可以用Java在代码中写死。能不写死更好。用对象装这些蓝牙的数据。完美。

**Comment by xiaoyaoyou1212** [comment]
@zhang40bu 已经添加获取服务、特征值、属性的相关方法，下面说的那个没太明白你可以自己写，如果需要在框架中添加你可以fork 后 pull request.
