### ISSUE TITLE
数据传输速度慢

### ISSUE THREAD

**Issue by xyxabcdiy** [xiaoyaoyou1212/BLE#6]
从手机发送数据开始，到设备接到数据后马上响应，时间间隔为60~100ms，蓝牙的数据传输速率应该不会这么慢啊，有没有什么好的解决方案？

**Comment by xiaoyaoyou1212** [comment]
@xyxabcdiy 传输速率这块目前没做具体测试，但是我用设备测试的时间一般在40ms-150ms之间，这个是从数据发送成功到收到设备响应数据的时间。具体优化没有研究，估计需要嵌入式那边优化吧，上层只是收发数据而已。
