### ISSUE TITLE
有两个Characteristic，怎么分开写数据？

### ISSUE THREAD

**Issue by BadDeveloper2022** [xiaoyaoyou1212/BLE#67]
有两个Characteristic，怎么分开写数据？
两个都绑定了，但是我看write方法没有指定通道啊
这也感觉每次写最后一个绑定的通道吧

**Comment by xiaoyaoyou1212** [comment]
一个类型的通道每次只能绑定一个，必须要使用完后解绑再继续绑定另一个通道

**Comment by BadDeveloper2022** [comment]
我自己重写了你的write方法，多加了参数
