### ISSUE TITLE
Ble的ScanCallback 用LeakCannary检测会发现内存泄漏问题

### ISSUE THREAD

**Issue by ContentPane** [xiaoyaoyou1212/BLE#68]
Ble的ScanCallback 用LeakCannary检测会发现内存泄漏,导致activity不能正确地回收,且onFinish回调和onTimeOut回调也不能正确触发,ViseBle的参数我也设置了,只能停止扫描而不能出发回调,后来我直接调用BluetoothAdapter.LeScanCallBack 和 BluetoothAdapter.startLeScan(callback)过时方法但不会发生内存泄漏问题.望周知~
![431547777988_ pic_hd](https://user-images.githubusercontent.com/28483504/51361438-bada4380-1b0a-11e9-9042-58d1f6165439.jpg)

**Comment by xiaoyaoyou1212** [comment]
谢谢指出，ViseBle这个当时就是考虑全局使用的，扫描的回调必须要指定同样的

**Comment by ContentPane** [comment]
后面我又用脚本测试了,发现用Android官方的扫描回调还是会内存泄漏 destroy的时候我已经停止扫描,而且把回调置空后还是没办法,看来Android官方把它设为过时也可能是这个bug的问题吧,不好意思是我搞错了~~实在抱歉!!! :(

**Comment by xiaoyaoyou1212** [comment]
@Rianney 客气了，技术需要在摸索和钻研中不断前进，很佩服你的细致和钻研精神~
