### ISSUE TITLE
getBluetoothLeScanner() 会返回空, 导致很多NPE

### ISSUE THREAD

**Issue by MAIMIHO** [xiaoyaoyou1212/BLE#8]
`public BluetoothLeScanner getBluetoothLeScanner() {
        if (!getLeAccess()) return null;
        synchronized(mLock) {
            if (sBluetoothLeScanner == null) {
                sBluetoothLeScanner = new BluetoothLeScanner(mManagerService);
            }
        }
        return sBluetoothLeScanner;
    }`

框架中很多地方调用了getBluetoothLeScanner() , 但是这个方法有可能返回null, 会导致很多NPE.
这几种情况会出现: 

-  蓝牙打开过程中bluetoothAdapter.getBluetoothLeScanner().startScan(leScanCallback); 
- 扫描过程中关掉了蓝牙bluetoothAdapter.getBluetoothLeScanner().stopScan(leScanCallback);

**Comment by xiaoyaoyou1212** [comment]
@MAIMIHO 问题已修复，谢谢建议！
