### ISSUE TITLE
我现在有两个蓝牙设备要和我的程序连接，一个可以连接，另一个不可以

### ISSUE THREAD

**Issue by alienzh** [xiaoyaoyou1212/BLE#9]
我现在有两个蓝牙设备要和我的程序连接，都是调用用的 ViseBluetooth.getInstance().connectByName(bleName, false, connectCallback); 一个可以连接，另一个不可以
不能连接的拿个没有任何回调，很奇怪

**Comment by xiaoyaoyou1212** [comment]
@alienzh 目前该库只能同时连接一个设备，如果要连接另外一个设备需断开第一个连接的设备。

**Comment by alienzh** [comment]
我明白了

**Comment by alienzh** [comment]
现在又遇到新的问题了，设备里面数据是不停的发送出来的，我通过IBleCallback接收到的数据，发现丢包了，或者有些数据重复了，而我又别的测试工具发现数据发送是正常的，请问下IBleCallback回调会出错么？这个设备下发数据是一秒两次或者一秒一次
